version: "3"

services:
  redis:
    image: "bitnami/redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis"
    
  mysql:
    container_name: mysql_db
    hostname: mysql_db
    image: "mysql:5.7"
    command: --init-file /config/initial.sql
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - "mysql_data:/var/lib/mysql"
      - ./initial.sql:/config/initial.sql

volumes:
  redis_data:
    driver: local

  mysql_data:
    driver: local